service: usaw-image

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "sbd-usaw-hackathon"
            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  usaw-tools:
    handler: handler.router
    events:
      - http:
          path: tools
          method: post
      - http:
          path: tools/detect
          method: put

# you can add CloudFormation resource templates here
resources:
  Resources:
    uSawS3:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sbd-usaw-hackhathon
